### ISSUE TITLE
Hardcoded path in dynamixel sdk

### ISSUE THREAD

**Issue by ghost** [squirrel-project/squirrel_driver#121]
Hi all,

in [dynamixel_tool.cpp line 97](https://github.com/squirrel-project/squirrel_driver/blob/indigo_dev/squirrel_control/src/dynamixel_sdk/dynamixel_tool.cpp#L97) the path to the model_info.list is hardcoded. However, the standard robotino setup does not install anything in that path. We should consider change that path to the [local resources in this package](https://github.com/squirrel-project/squirrel_driver/tree/indigo_dev/squirrel_control/dynamixel/models) or change the robot setup so that those files are installed in the predefined path `/usr/local/dynamixel/models/model_info.list`.

Best

**Comment by ipa-nhg** [comment]
@lokalmatador could you please fix this?

**Comment by ghost** [comment]
Well, not within the next two weeks - I'm leaving in an hour for holidays. You could ask Simon Haller, he also knows the problem. We originally were not able to export this file within the cmake build (sth failed). We thus temporarily moved it there. If you know how to do the former, please go ahead :) I'd be happy. Otherwise, in the meantime you can just copy the file to the respective location and we can fix it when I'm back. Ugly solution but at least only temporarily. Sorry for the delay.

**Comment by ghost** [comment]
@smhaller can you maybe fix this when you're back? Seems we totally forgot about it :D

**Comment by ghost** [comment]
Fixed. Please close.

**Comment by ipa-nhg** [comment]
@lokalmatador could you please open a Pull Request?

**Comment by ghost** [comment]
should be there now

**Comment by ipa-nhg** [comment]
can be closed as soon as https://github.com/squirrel-project/squirrel_driver/pull/133 is merged

**Comment by ghost** [comment]
Can't close it :(

**Comment by ipa-nhg** [comment]
Fixed by https://github.com/squirrel-project/squirrel_driver/pull/133 , can be closed
