### ISSUE TITLE
Base control unexpected behaviours

### ISSUE THREAD

**Issue by ghost** [squirrel-project/squirrel_driver#123]
Dear all,

I noticed that `/squirrel_control_node` sometimes does not release the control of the base (and probably of the arm too). I also experienced this straight after booting the robot. For instance, it happens to me that I could not reposition the robot with the joystick cause the low level controller moved the robot to pose where the robot was switched on. 

I think `/squirrel_control_node` should execute the control loop if and only if requested. It might be also useful to create a service that kills the control loop just in case the a controller has been called via topic `/trajectory_trajectory_controller/command` and without the action server/client.

**Comment by mzillich** [comment]
Is this not, why we had the twist multiplexer?

**Comment by ipa-nhg** [comment]
are you starting a teleop node for ROS or the festo upstart control is controlling the joystick?

**Comment by ghost** [comment]
So that happed to me a couple of times. I joysticked the robot using the low level driver by FESTO, no ROS teleop. What I noticed is that something was publishing `/cmd_rotatory`.

**Comment by ghost** [comment]
So what's the issue then here? Can we be more precise? The controller does not lock the base, as @mzillich suggests, this is related to the twist multiplexer.

**Comment by ipa-nhg** [comment]
was this solved?

**Comment by ghost** [comment]
I guess so, yes. @smhaller and @philkark was this finally fixed?
