### ISSUE TITLE
stop publishing to cmd_vel

### ISSUE THREAD

**Issue by mzillich** [squirrel-project/squirrel_driver#129]
Currently squirrel_controller publishes commands to the joints and base constantly, as part of the SquirrelHWControlLoop::update() loop. It should hovever only send commands while executing a trajectory. Otherwise the squirrel_controller will "freeze" the base, and prevent move_base and even the joystick from moving the base.
So a flag or something "executing_trajectgory" would need to be added.

**Comment by ghost** [comment]
We'll have a look at it today.

We will fix this by adding a topic for start and stopping the publisher - we do not want to interfere with the internals of ros_control.

**Comment by ghost** [comment]
Fixed. The controller now only publishes to /cmd_rotatory upon receiving a new trajectory; after the goal has been reached, nothing is published to the base anymore from the controller side (not the arm!). This is a dirty hack that violates ros_control.

Please test and close.

**Comment by ipa-nhg** [comment]
@lokalmatador thanks! could you please open a Pull Request?

**Comment by ipa-nhg** [comment]
This can be closed as soon as https://github.com/squirrel-project/squirrel_driver/pull/133 is merged

**Comment by ghost** [comment]
Can't close :(

**Comment by ipa-nhg** [comment]
merged https://github.com/squirrel-project/squirrel_driver/pull/133 can be closed
