### ISSUE TITLE
Compilation problem

### ISSUE THREAD

**Issue by ghost** [squirrel-project/squirrel_driver#167]
Missed `add_dependencies(squirrel_hw_control_loop squirrel_safety_msgs_gencpp)` [at line 94](https://github.com/squirrel-project/squirrel_driver/blob/indigo_dev/squirrel_control/CMakeLists.txt#L94)

**Comment by ipa-nhg** [comment]
Done https://github.com/squirrel-project/squirrel_driver/pull/173 
Thanks!
