### ISSUE TITLE
Where's the launch file?

### ISSUE THREAD

**Issue by ghost** [squirrel-project/squirrel_driver#86]
squirrel_sensing_node does not provide anymore a launch file. why? can we please put that back there for specifying relevant devices instead of passing them as CL arguments? They generally should no change on the same robot given that proper udev rules are there.

**Comment by ipa-nhg** [comment]
this one https://github.com/squirrel-project/squirrel_robotino/blob/indigo_dev/robotino_bringup/launch/sensing.launch ?
@mzillich

**Comment by ghost** [comment]
Yep.

**Comment by mzillich** [comment]
This is in now, so I think we can close this. cheers.
